# Generated by Django 5.1.7 on 2025-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
