# Generated by Django 5.1.7 on 2025-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_documents_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='file_path',
        ),
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
